(* ppcLib - generated by L3 - Mon Jun 27 13:52:14 2022 *)
structure ppcLib :> ppcLib =
struct
open HolKernel boolLib bossLib
open utilsLib ppcTheory
val () = (numLib.prefer_num (); wordsLib.prefer_word ())
fun ppc_compset thms =
   utilsLib.theory_compset (thms, ppcTheory.inventory)
end